site_name: ezglossary
theme:
  name: material
  features:
    navigation.path
    navigation.indexes
    navigation.tabs

extra_css:
  - css/extra.css

nav:
  - home: index.md
  - getting started: getting_started.md
  - usage:
    - usage/index.md
    - usage/definition.md
    - usage/linking.md
    - usage/summary.md
    - usage/sections.md
  - definitions: definitions.md
  - configuration: configuration.md
  - release notes: releases.md

markdown_extensions:
  - toc:
      permalink: true
      separator: "-"
  - attr_list
  - def_list
  - tables
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - callouts
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - md_in_html
  - mkdocs-click

plugins:
  - search
  - ezglossary:
      strict: true
      list_definitions: true
      list_references: true
      tooltip: full
      sections:
        - setting
        - term
        - demo
        - configuration
